### PR TITLE
Disable ctest on MacOS

### PR DESCRIPTION
**Pull request by rhyspoulton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rhyspoulton** [comment]
This was closed as it should be resolved by the upstream package.

**Comment by duncanmmacleod** [comment]
> This was closed as it should be resolved by the upstream package.

@rhyspoulton, what's the ETA on a new release. If any migrations or rebuilds come along before that we will need to include this patch anyway.

**Comment by rhyspoulton** [comment]
So I am checking with Florent as this test passed in the pull request: https://github.com/conda-forge/gwollum-feedstock/pull/31 but not the merge request: https://github.com/conda-forge/gwollum-feedstock/commit/470bad58b09b8c5946e508cd32b824ed7e90d112 so I think this must be a flaky test. I am reruning the test again to see if it works.

**Comment by rhyspoulton** [comment]
Reopening so a flakey test is not included in the conda build.

**Pull request merged**
